services:
  tododb:
    container_name: tododb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TodoDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_todo:/var/lib/postgressql/data/
